### ISSUE TITLE
Code for bypassing ngrok cors policy not working

### ISSUE THREAD

**Issue by anujnegi341** [GavinLonDigital/movie-gold-v1#1]
I am using the same appConfig file as yours still the error is coming in the API, for CORS

here's SS of the error
![image](https://user-images.githubusercontent.com/66074635/229353770-4a501135-e670-4251-b854-72101f2c1fe9.png)

and  app code is : 
import axios from 'axios';

export default axios.create({
    baseURL:'https://9c96-103-106-239-104.ap.ngrok.io',
    headers: {"ngrok-skip-browser-warning": "true"}
});

**Comment by dimov05** [comment]
First you have to setup your own tunnel to your localhost:80**. You should register for free at this link: https://dashboard.ngrok.com/get-started/setup . 
After this you have to enter the dropdown menu "tunnels" and there select "Agents". You must create your own Agent redirecting to your localhost. In the attached image you can see my 'config'.
![Ngrok](https://user-images.githubusercontent.com/94742531/229466538-a789b4df-2753-4acd-bca9-1d05603df402.jpg)
At last you have to use the generated link and paste it in the 'axiosConfig.js' file on 'baseURL'.

**Comment by anujnegi341** [comment]
I used my local Url instead of ngrok tunneling for time being, will try this too later, 
Thanks for the reply @GavinLonDigital
